# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0757f480d79d5407449bd003706fb10933b3857c8c6dce02eb2bf06ff9531a63a7ce3ab4cdf3a7d6d0b468dc7f976977b72274176ac72039ae5b16518a0a71

test:
  secret_key_base: 918be70bf964f5edb40bfe87606c922e5f13b9ce879c81ecbddd2b92be8c960e7aea2381274960a52d7038cbf45a36e4b16b074e2e3410208f35252a5d756cf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
